// All the questions, prompts, and games.
// Pack types:
//   quiz     – pick your own answer AND guess your partner's (score each other)
//   pick     – two options, both choose, see where you match (This or That / Would You Rather)
//   who      – "who's more likely to", each picks a name
//   nhie     – never have I ever (I have / never)
//   open     – written answers, revealed side by side
//   ynm      – yes / maybe / no; only MUTUAL yes/maybe items are ever revealed
//   lovelang – love language quiz, scored per person

export const CATEGORIES = [
  { id: 'quiz', title: 'How Well Do You Know Me?', blurb: 'Answer for yourself, then guess for them. Scores are kept.' },
  { id: 'thisorthat', title: 'This or That', blurb: 'Quick picks. See how in sync you are.' },
  { id: 'wyr', title: 'Would You Rather', blurb: 'Impossible choices, revealed together.' },
  { id: 'who', title: "Who's More Likely To", blurb: 'Point fingers. Lovingly.' },
  { id: 'nhie', title: 'Never Have I Ever', blurb: 'Confessions, revealed once you both finish.' },
  { id: 'talk', title: 'Deep Talks', blurb: 'Write it out, then read each other’s answers.' },
  { id: 'about', title: 'About You Two', blurb: 'Personality stuff for the both of you.' },
];

export const SPICY_CATEGORIES = [
  { id: 'desire', title: 'Desire Match', blurb: 'Yes / Maybe / No. Only things you BOTH want get revealed. No awkward no’s.' },
  { id: 'spicyquiz', title: 'Spicy Quizzes', blurb: 'How well do you know what they like?' },
  { id: 'spicyplay', title: 'Spicy Picks', blurb: 'This or That, Would You Rather & more, after dark.' },
  { id: 'spicytalk', title: 'Pillow Talk', blurb: 'Say it in writing first.' },
];

export const PACKS = [
  // ───────────────────────── HOW WELL DO YOU KNOW ME ─────────────────────────
  {
    id: 'quiz-basics', type: 'quiz', cat: 'quiz', emoji: '🧩', title: 'The Basics',
    items: [
      { q: 'Your ideal Sunday morning?', o: ['Sleeping in until noon', 'Slow breakfast + coffee', 'Up early and productive', 'Cuddled up with a show'] },
      { q: 'Pick a superpower:', o: ['Teleportation', 'Reading minds', 'Flying', 'Pausing time'] },
      { q: 'Your dream vacation vibe?', o: ['Beach and doing nothing', 'Big city exploring', 'Cabin in the mountains', 'Road trip, no plan'] },
      { q: 'What drains your social battery fastest?', o: ['Big parties', 'Small talk with strangers', 'Phone calls', 'Being "on" all day'] },
      { q: 'When you’re stressed, you usually…', o: ['Go quiet and need space', 'Talk it out', 'Clean or organize something', 'Distract myself (phone, shows, games)'] },
      { q: 'Favorite season?', o: ['Spring', 'Summer', 'Fall', 'Winter'] },
      { q: 'Which would you rather receive?', o: ['A long handwritten note', 'A surprise gift', 'A whole planned day together', 'A massage'] },
      { q: 'Random movie night, you pick:', o: ['Comedy', 'Horror / thriller', 'Rom-com', 'Action / sci-fi'] },
      { q: 'Your ideal pet situation?', o: ['A dog', 'A cat', 'Both, chaos house', 'Something weird (lizard, ferret…)'] },
      { q: 'Karaoke night, you are:', o: ['Belting a power ballad', 'Rapping every word', 'Duet with my person', 'Absolutely not singing'] },
    ],
  },
  {
    id: 'quiz-food', type: 'quiz', cat: 'quiz', emoji: '🍕', title: 'Food & Cravings',
    items: [
      { q: 'Your last meal on earth?', o: ['Pizza', 'Sushi', 'A big steak dinner', 'Pasta'] },
      { q: 'Breakfast order?', o: ['Sweet (pancakes, waffles)', 'Savory (eggs, bacon)', 'Just coffee', 'Breakfast burrito / sandwich'] },
      { q: 'Spice tolerance?', o: ['Mild, please', 'Medium', 'Hot', 'Make me cry'] },
      { q: 'Fast food emergency, you go to:', o: ['Chick-fil-A', 'Taco Bell', 'McDonald’s', 'Chipotle'] },
      { q: 'The snack you’d fight someone for?', o: ['Chips', 'Candy', 'Ice cream', 'Popcorn'] },
      { q: 'Pineapple on pizza?', o: ['Absolutely yes', 'Hard no', 'Only with ham', 'I eat whatever’s there'] },
      { q: 'Caffeine of choice?', o: ['Black coffee', 'Sweet iced latte', 'Energy drink', 'No caffeine for me'] },
      { q: 'Favorite cuisine?', o: ['Mexican', 'Italian', 'Asian (Japanese, Thai, Chinese…)', 'American comfort food'] },
      { q: 'In the kitchen you are:', o: ['An actual chef', 'Can follow a recipe', 'Microwave master', 'The dishwasher'] },
      { q: 'Dessert pick?', o: ['Anything chocolate', 'Cheesecake', 'Ice cream', 'Something fruity'] },
    ],
  },
  {
    id: 'quiz-love', type: 'quiz', cat: 'quiz', emoji: '💘', title: 'Love & Romance',
    items: [
      { q: 'Your love language, gut answer?', o: ['Words of affirmation', 'Quality time', 'Physical touch', 'Gifts / acts of service'] },
      { q: 'The best kind of date?', o: ['Fancy dinner', 'Cozy night in', 'Something adventurous', 'Spontaneous drive somewhere'] },
      { q: 'When did you first realize you liked me?', o: ['Basically right away', 'After a few hangouts', 'After one specific moment', 'It snuck up on me'] },
      { q: 'Most romantic gesture?', o: ['A surprise trip', 'A love letter', 'Cooking a special dinner', 'Remembering a tiny detail I said'] },
      { q: 'Ideal amount of texting during the day?', o: ['Constant updates', 'A few check-ins', 'Just the important stuff', 'Memes only'] },
      { q: 'PDA level?', o: ['Hands off in public', 'Hand-holding max', 'Kisses are fine', 'I don’t care who’s watching'] },
      { q: 'Best way to make up after a fight?', o: ['Talk it out right away', 'Space first, then talk', 'A long hug fixes most things', 'Food. Always food.'] },
      { q: 'Anniversary plans?', o: ['Big night out', 'A trip away', 'Quiet and sentimental at home', 'Recreate our first date'] },
      { q: 'Favorite way to fall asleep together?', o: ['Big spoon', 'Little spoon', 'Completely tangled up', 'Touching, but with my own space'] },
      { q: 'Which compliment hits hardest?', o: ['About my looks', 'About my brain', 'About how I make you feel', 'About something I worked hard on'] },
    ],
  },
  {
    id: 'quiz-quirks', type: 'quiz', cat: 'quiz', emoji: '🙃', title: 'Habits & Quirks',
    items: [
      { q: 'Your phone battery is usually at…', o: ['Always charged', '50% and fine', 'Living on 4%', 'Dead somewhere'] },
      { q: 'Morning person or night owl?', o: ['Total morning person', 'Night owl forever', 'Depends on the day', 'Tired at all hours'] },
      { q: 'Your room is usually…', o: ['Spotless', 'Organized chaos', 'The chair has a clothes pile', 'Don’t look'] },
      { q: 'Your shower is a…', o: ['5-minute speedrun', '10–15 minutes', '30+ minute concert', 'Depends how much thinking I need'] },
      { q: 'How many alarms do you set?', o: ['One', '2–3', '5 or more', 'I wake up naturally'] },
      { q: 'You’re usually…', o: ['Early', 'Right on time', '5–10 minutes late', '"On my way" (still in bed)'] },
      { q: 'Your texting style?', o: ['Full sentences, punctuation', 'all lowercase no punctuation', 'Voice memos', 'Emojis and reactions do the talking'] },
      { q: 'In a group project you’re the…', o: ['Leader', 'Quiet hard worker', 'Idea person', 'Moral support'] },
      { q: 'Your comfort rewatch is…', o: ['A sitcom', 'An animated show', 'Trashy reality TV', 'The same movie series again'] },
      { q: 'What do you do the most?', o: ['Overthink', 'Procrastinate', 'Overcommit', 'Overshare'] },
    ],
  },
  {
    id: 'quiz-future', type: 'quiz', cat: 'quiz', emoji: '🔮', title: 'Dreams & Future',
    items: [
      { q: 'Dream place to live?', o: ['Big city', 'Suburbs', 'Small town / countryside', 'By the ocean'] },
      { q: 'How many kids, if any?', o: ['None', 'One', 'Two', 'Three or more'] },
      { q: 'If money didn’t matter, you’d…', o: ['Travel the world', 'Start something of my own', 'Honestly keep doing my thing', 'Retire and chill'] },
      { q: 'Wedding style?', o: ['Big party', 'Small and intimate', 'Elope', 'Destination wedding'] },
      { q: 'Must-have dream home feature?', o: ['Huge kitchen', 'Pool or hot tub', 'Home theater', 'A big yard'] },
      { q: 'In 10 years you want to be known for…', o: ['Crushing my career', 'Being a great partner / parent', 'Being fun and adventurous', 'Being kind'] },
      { q: 'Retirement vibe?', o: ['Beach house', 'Traveling nonstop', 'Garden and grandkids', 'Still working on passion projects'] },
      { q: 'Biggest focus right now?', o: ['Career / school', 'Health and fitness', 'Money', 'Our relationship'] },
      { q: 'Dream car?', o: ['Something fast', 'Something big and practical', 'Classic / vintage', 'I don’t care about cars'] },
      { q: 'Bucket-list experience?', o: ['Skydiving', 'Seeing the northern lights', 'An African safari', 'Living abroad for a year'] },
    ],
  },
  {
    id: 'quiz-hottakes', type: 'quiz', cat: 'quiz', emoji: '🌶️', title: 'Hot Takes',
    items: [
      { q: 'Biggest pet peeve?', o: ['Loud chewing', 'People being late', 'Slow walkers', 'Dishes left in the sink'] },
      { q: 'Socks in bed?', o: ['Always', 'Never', 'Only when it’s cold', 'Start on, kicked off at 2am'] },
      { q: 'Toilet paper roll goes…', o: ['Over', 'Under', 'Whatever’s fastest', 'There’s a debate?'] },
      { q: 'Is a hot dog a sandwich?', o: ['Yes', 'No', 'It’s a taco', 'I refuse to engage'] },
      { q: 'You find $100 on the street. You…', o: ['Spend it on food', 'Buy clothes', 'Save it', 'Spend it on you'] },
      { q: 'Most overrated thing?', o: ['Brunch', 'Camping', 'Clubs / bars', 'Social media'] },
      { q: 'Worst chore?', o: ['Dishes', 'Laundry', 'Cleaning the bathroom', 'Taking out the trash'] },
      { q: 'Cereal or milk first?', o: ['Cereal first, obviously', 'Milk first (chaos)', 'Dry cereal', 'I don’t eat cereal'] },
      { q: 'Ideal room temperature?', o: ['Freezing', 'Cool', 'Warm', 'Sauna'] },
      { q: 'Someone texts you "k". It means…', o: ['Totally fine', 'Passive aggressive', 'They’re mad', 'Grounds for a breakup'] },
    ],
  },

  // ───────────────────────── THIS OR THAT ─────────────────────────
  {
    id: 'tot-everyday', type: 'pick', cat: 'thisorthat', emoji: '⚖️', title: 'Everyday',
    items: [
      ['Coffee', 'Tea'], ['Beach', 'Mountains'], ['Sunrise', 'Sunset'], ['Texting', 'Calling'], ['Dogs', 'Cats'],
      ['Binge a show', 'Movie theater'], ['Sweet', 'Salty'], ['Summer', 'Winter'], ['Pizza', 'Burgers'],
      ['Books', 'Podcasts'], ['Shower at night', 'Shower in the morning'], ['Big party', 'Small hangout'],
      ['City', 'Countryside'], ['Pancakes', 'Waffles'], ['Planner', 'Spontaneous'], ['Hoodie', 'Jacket'],
    ],
  },
  {
    id: 'tot-dates', type: 'pick', cat: 'thisorthat', emoji: '🕯️', title: 'Date Night',
    items: [
      ['Fancy dinner', 'Food truck'], ['Stay in', 'Go out'], ['Movie', 'Mini golf'], ['Cook together', 'Order takeout'],
      ['Bowling', 'Arcade'], ['Picnic', 'Rooftop bar'], ['Concert', 'Comedy show'], ['Board games', 'Video games'],
      ['Matching outfits', 'Absolutely not'], ['Dessert first', 'Dessert last'], ['Slow dance in the kitchen', 'Karaoke duet'],
      ['Stargazing', 'Drive-in movie'],
    ],
  },
  {
    id: 'tot-travel', type: 'pick', cat: 'thisorthat', emoji: '✈️', title: 'Travel',
    items: [
      ['Beach resort', 'Cabin in the woods'], ['Plan every hour', 'Wing it'], ['Window seat', 'Aisle seat'],
      ['Road trip', 'Flight'], ['Hotel', 'Airbnb'], ['Museums', 'Nightlife'], ['Europe', 'Asia'],
      ['Camping', 'Glamping'], ['Souvenirs', 'Just photos'], ['Backpacking on a budget', 'Full luxury'],
      ['Theme park', 'National park'], ['Cruise', 'Train across a country'],
    ],
  },

  // ───────────────────────── WOULD YOU RATHER ─────────────────────────
  {
    id: 'wyr-silly', type: 'pick', cat: 'wyr', emoji: '🤪', title: 'Silly',
    items: [
      ['Fight one horse-sized duck', 'Fight 100 duck-sized horses'],
      ['Only be able to whisper', 'Only be able to shout'],
      ['Have a rewind button for your life', 'Have a pause button'],
      ['Talk to animals', 'Speak every human language'],
      ['Never use your phone again', 'Never eat your favorite food again'],
      ['Have a personal chef', 'Have a personal driver'],
      ['Live in a treehouse', 'Live on a houseboat'],
      ['Always be 10 minutes late', 'Always be 20 minutes early'],
      ['Unlimited free flights', 'Unlimited free food'],
      ['Be famous', 'Be rich and unknown'],
      ['Have hiccups forever', 'Always feel like you’re about to sneeze'],
      ['Have a theme song play when you walk in', 'Have a laugh track for everything you say'],
      ['Only wear crocs forever', 'Only wear a suit forever'],
    ],
  },
  {
    id: 'wyr-us', type: 'pick', cat: 'wyr', emoji: '💞', title: 'Us Edition',
    items: [
      ['Go on a spontaneous trip together tomorrow', 'Plan a dream trip a year from now'],
      ['Have a date night every week', 'Have one big adventure every month'],
      ['Read my mind for a day', 'Have me read yours'],
      ['Relive our first date', 'Fast-forward to see us in 10 years'],
      ['Only be able to text each other', 'Only be able to call each other'],
      ['Get matching tattoos', 'Have a couple song we play everywhere'],
      ['Tiny apartment in a cool city together', 'Big house in the middle of nowhere together'],
      ['A love letter from me every week', 'A surprise date from me every month'],
      ['Lose every photo of us', 'Lose every text we’ve sent'],
      ['Our love story becomes a movie', 'Our love story becomes a book'],
      ['Swap bodies for a day', 'Swap lives (jobs, friends) for a week'],
      ['Spend a whole day in bed together', 'Spend a whole day out exploring'],
    ],
  },

  // ───────────────────────── WHO'S MORE LIKELY ─────────────────────────
  {
    id: 'who-fun', type: 'who', cat: 'who', emoji: '👉', title: 'The Classics',
    items: [
      'Cry at a movie', 'Get lost even with GPS', 'Forget an anniversary', 'Survive a zombie apocalypse',
      'Eat the last slice without asking', 'Fall asleep first during a movie', 'Become famous',
      'Spend all their money on something dumb', 'Adopt a pet on impulse', 'Laugh at the worst possible moment',
      'Text "on my way" while still in bed', 'Win a game show', 'Get a random tattoo on vacation',
      'Say "I love you" first in a day', 'Be the better cook',
    ],
  },
  {
    id: 'who-chaos', type: 'who', cat: 'who', emoji: '🔥', title: 'Chaos Edition',
    items: [
      'Get arrested for something stupid', 'Go viral online', 'Set off the smoke alarm cooking',
      'Talk their way out of a ticket', 'Lose a fight to a goose', 'Fall for an obvious scam',
      'Lose their keys twice in one day', 'Sleep through an alarm on a big day', 'Buy something useless at 2am',
      'Be the last one to leave a party', 'Hold a grudge over a board game', 'Confidently sing the wrong lyrics',
      'Accidentally like an old photo while stalking someone', 'Become best friends with a stranger in a bathroom line',
      'Start a conspiracy theory',
    ],
  },

  // ───────────────────────── NEVER HAVE I EVER ─────────────────────────
  {
    id: 'nhie-classic', type: 'nhie', cat: 'nhie', emoji: '🙊', title: 'Classic',
    items: [
      'Pretended to like a gift', 'Snooped through someone’s phone', 'Stalked an ex on social media',
      'Lied about my age', 'Fallen asleep in class or at work', 'Eaten food off the floor', 'Ghosted someone',
      'Cried to get out of trouble', 'Gone skinny dipping', 'Broken a bone', 'Been on a blind date',
      'Re-gifted a present', 'Faked being sick to skip something', 'Googled my partner before we dated',
      'Pretended to know a song I didn’t know',
    ],
  },

  // ───────────────────────── DEEP TALKS ─────────────────────────
  {
    id: 'talk-closer', type: 'open', cat: 'talk', emoji: '🫶', title: 'Get Closer',
    items: [
      'If you could have dinner with anyone, dead or alive, who and why?',
      'What would a perfect day look like for you, start to finish?',
      'What’s something you’ve always wanted to do but haven’t yet? What’s stopping you?',
      'What are you most grateful for in your life right now?',
      'If you could change one thing about how you were raised, what would it be?',
      'What’s your single most treasured memory?',
      'What’s something you’ve never told anyone — or barely anyone?',
      'If you knew you had one year left, what would you change about how you live?',
      'What’s a belief you held strongly that you’ve since changed your mind about?',
      'What’s something about yourself you’re still learning to like?',
    ],
  },
  {
    id: 'talk-us', type: 'open', cat: 'talk', emoji: '👫', title: 'Just Us',
    items: [
      'What was your very first impression of me?',
      'When did you know you were falling for me?',
      'What’s your favorite memory of us so far?',
      'What’s something I do that makes you feel loved — that I probably don’t realize?',
      'What’s a small thing I do that you secretly find adorable?',
      'What’s one thing you’d love for us to do more often?',
      'What song makes you think of us?',
      'What’s the moment you felt closest to me?',
      'What do you think our biggest strength as a couple is?',
      'Describe us as a couple in three words.',
      'What’s something you’ve learned from me?',
    ],
  },
  {
    id: 'talk-future', type: 'open', cat: 'talk', emoji: '🏡', title: 'Future Us',
    items: [
      'Where do you see us in 5 years?',
      'What does your ideal everyday life together look like?',
      'What’s a tradition you want us to start?',
      'Name a place we HAVE to travel to together.',
      'What’s something you want us to accomplish as a team?',
      'What’s one thing from your family you want to bring into ours — and one you’d leave behind?',
      'What does a "rich life" mean to you — money, time, people, something else?',
      'What’s an adventure you want us to have in the next couple years?',
      'What’s something you hope never changes about us?',
      'How do you picture our home?',
    ],
  },
  {
    id: 'talk-honest', type: 'open', cat: 'talk', emoji: '💬', title: 'Honest Hour',
    items: [
      'What’s something I could do to make you feel more supported right now?',
      'Is there anything you’ve been wanting to tell me but haven’t?',
      'When do you feel most appreciated by me?',
      'What’s something you’re stressed about that I might not know?',
      'What’s one thing we could do better when we disagree?',
      'What’s a need you feel shy asking for?',
      'How can I love you better this month?',
      'What’s something you’re proud of yourself for lately?',
      'What’s something I did recently that meant more than I probably realized?',
      'What’s one thing you want us to work on together?',
    ],
  },
  {
    id: 'talk-hypo', type: 'open', cat: 'talk', emoji: '🎲', title: 'Hypotheticals',
    items: [
      'If we were a famous duo, who would we be?',
      'You get one free tattoo of anything, zero regrets. What is it?',
      'If you could live in any fictional world, which one?',
      'What would your walk-up song be?',
      'If our relationship were a movie, what’s the title — and who plays us?',
      'You have $10,000 that must be spent in 24 hours. Go.',
      'What’s the weirdest thing you believed as a kid?',
      'What’s your most useless talent?',
      'What would we name our future pet, and what is it?',
      'If you could master one skill overnight, what would it be?',
    ],
  },

  // ───────────────────────── ABOUT YOU TWO ─────────────────────────
  {
    id: 'lovelang', type: 'lovelang', cat: 'about', emoji: '💝', title: 'Love Language Quiz',
    blurb: 'Pick which one would mean more to you. Find out how you each feel loved.',
    items: [
      [['A sweet text out of nowhere saying you’re proud of me', 'W'], ['An evening together with our phones put away', 'Q']],
      [['A little gift because something made you think of me', 'G'], ['You handle a chore I’ve been dreading', 'A']],
      [['A long hug when I get home', 'T'], ['You tell me exactly why you love me', 'W']],
      [['A whole day trip, just us', 'Q'], ['A surprise package from you in the mail', 'G']],
      [['You make me breakfast without me asking', 'A'], ['You hold my hand while we walk', 'T']],
      [['You hype me up in front of other people', 'W'], ['You fix something that’s been bugging me', 'A']],
      [['Cuddling on the couch', 'T'], ['A meaningful souvenir from your trip', 'G']],
      [['A deep conversation late at night', 'Q'], ['A back rub after a long day', 'T']],
      [['A handwritten note I find later', 'W'], ['You remember something small I wanted and get it for me', 'G']],
      [['You run an errand so I can rest', 'A'], ['You plan a date just for us', 'Q']],
      [['You kiss me goodbye every time', 'T'], ['You say "I love you" and really mean it', 'W']],
      [['You surprise me with my favorite snack', 'G'], ['You help with a project I’m stressed about', 'A']],
      [['You give me your full attention when I talk', 'Q'], ['You tell me I look good', 'W']],
      [['You take care of me when I’m sick', 'A'], ['You sit close to me, even in public', 'T']],
      [['You make time for me even when you’re busy', 'Q'], ['A birthday present that shows you really know me', 'G']],
    ],
  },

  // ═════════════════════════ SPICY (18+) ═════════════════════════
  {
    id: 'desire-1', type: 'ynm', cat: 'desire', spicy: true, emoji: '🔥', title: 'Desire Match: Warm-Up',
    blurb: 'Answer honestly. Only things you’re BOTH a yes or maybe on will show up.',
    items: [
      'Long make-out sessions', 'Massage with oil', 'Showering together', 'Morning sex', 'Sexting during the day',
      'Sending pics', 'Dirty talk', 'Lingerie / dressing up', 'Leaving the lights on', 'Doing it in front of a mirror',
      'Quickies', 'An all-night marathon', 'A hotel weekend just for this', 'Giving oral', 'Receiving oral',
      'Trying a brand new position', 'Slow, sensual, take-our-time sex', 'Strip tease', 'Lap dance',
      'Skinny dipping', 'Teasing each other under the table',
    ],
  },
  {
    id: 'desire-2', type: 'ynm', cat: 'desire', spicy: true, emoji: '⛓️', title: 'Desire Match: Wild',
    blurb: 'The bolder stuff. Mutual yes/maybe only. Nobody sees your no’s.',
    items: [
      'Blindfolds', 'Tying hands', 'Handcuffs', 'Me being in charge', 'You being in charge', 'Hair pulling',
      'Spanking', 'Biting / scratching', 'Leaving marks', 'Toys on me', 'Toys on you', 'Using toys together',
      'Role-play', 'Watching something spicy together', 'Reading something spicy out loud', 'Edging / teasing',
      'Ice or temperature play', 'Food play (whipped cream, etc.)', 'Doing it in the car', 'Doing it outdoors',
      'Somewhere we might get caught', 'Rough sex', 'Light choking (talk first)', 'Anal play',
      'Praise ("good girl / good boy")', 'Filming something (just for us)', 'Video / phone sex when apart',
      'Sex games (dice, cards)',
    ],
  },
  {
    id: 'spicyquiz-1', type: 'quiz', cat: 'spicyquiz', spicy: true, emoji: '😏', title: 'Bedroom Secrets',
    items: [
      { q: 'Your favorite time for it?', o: ['Morning', 'Afternoon delight', 'Late night', 'Whenever, honestly'] },
      { q: 'Lights?', o: ['On', 'Off', 'Candles / dim', 'Doesn’t matter'] },
      { q: 'What turns you on fastest?', o: ['Neck kisses', 'Dirty talk', 'Seeing you dressed up', 'Being teased'] },
      { q: 'Favorite position category?', o: ['Me on top', 'You on top', 'From behind', 'Side by side / spooning'] },
      { q: 'Ideal frequency?', o: ['Every day', 'A few times a week', 'Once a week', 'Quality over quantity'] },
      { q: 'Most underrated place to be kissed?', o: ['Neck', 'Ears', 'Inner thighs', 'Lower back / hips'] },
      { q: 'Quickie or all-nighter?', o: ['Quickie every time', 'Long and slow', 'A mix of both', 'Quickie that turns into an all-nighter'] },
      { q: 'Wildest place you’d do it?', o: ['The car', 'The shower', 'Outdoors somewhere', 'Somewhere we could get caught'] },
      { q: 'Your vibe in bed?', o: ['Dominant', 'Submissive', 'Switch', 'Depends on the mood'] },
      { q: 'Best foreplay?', o: ['Making out', 'Massage', 'Teasing over text all day', 'Undressing slowly'] },
    ],
  },
  {
    id: 'spicyquiz-2', type: 'quiz', cat: 'spicyquiz', spicy: true, emoji: '💋', title: 'Turn-Ons',
    items: [
      { q: 'What outfit on me drives you craziest?', o: ['Lingerie / nice underwear', 'Wearing your clothes', 'Dressed up to go out', 'Nothing at all'] },
      { q: 'Favorite kind of kiss?', o: ['Slow and soft', 'Deep and intense', 'Neck kisses', 'Lip biting'] },
      { q: 'Sexiest thing to hear?', o: ['"I want you"', '"You’re so hot"', 'Your name, moaned', 'Being told exactly what to do'] },
      { q: 'You want more…', o: ['Foreplay', 'Spontaneity', 'Trying new things', 'Eye contact'] },
      { q: 'Toys?', o: ['Love them', 'Open to them', 'Curious but nervous', 'Not my thing'] },
      { q: 'Hair pulling?', o: ['Yes please', 'Gently', 'Only if I start it', 'No thanks'] },
      { q: 'The morning after, you want…', o: ['Round two', 'Cuddles', 'Breakfast', 'Back to sleep'] },
      { q: 'The best tease?', o: ['A text in the middle of the day', 'A look across the room', 'A touch under the table', 'A pic'] },
      { q: 'Role-play?', o: ['Absolutely', 'With the right scenario', 'I’d laugh too much', 'No'] },
      { q: 'Favorite non-obvious place to be touched?', o: ['Neck', 'Back', 'Thighs', 'Hair / scalp'] },
    ],
  },
  {
    id: 'spicy-tot', type: 'pick', cat: 'spicyplay', spicy: true, emoji: '🌙', title: 'This or That: After Dark',
    items: [
      ['Lights on', 'Lights off'], ['Morning', 'Night'], ['Slow', 'Rough'], ['Quickie', 'All night'],
      ['Lingerie', 'Nothing'], ['Shower', 'Bed'], ['Top', 'Bottom'], ['Bite', 'Scratch'], ['Whisper', 'Moan'],
      ['Bedroom', 'Anywhere else'], ['Blindfold', 'Handcuffs'], ['Teasing', 'Straight to it'],
      ['Watching in a mirror', 'Eyes locked on each other'], ['Dirty texts', 'Spicy pics'], ['Being undressed', 'Undressing you'],
    ],
  },
  {
    id: 'spicy-wyr', type: 'pick', cat: 'spicyplay', spicy: true, emoji: '😈', title: 'Would You Rather: Spicy',
    items: [
      ['Be teased for an hour', 'Get it right now'],
      ['Have me in charge for a night', 'Be in charge for a night'],
      ['Somewhere risky', 'Somewhere luxurious'],
      ['Only kissing for a week', 'Everything except kissing for a week'],
      ['Get a full-body massage', 'Give one (that leads somewhere)'],
      ['A spicy pic while you’re at work', 'A dirty voice memo before bed'],
      ['Try a new position every week', 'Perfect your favorite one'],
      ['Sexy role-play', 'Sexy dress-up'],
      ['Have me tell you exactly what I want', 'Have me show you'],
      ['Wake up to me under the covers', 'Fall asleep after a long session'],
      ['Blindfolded', 'Tied up'],
      ['Hotel weekend', 'Cabin weekend where clothes aren’t allowed'],
      ['Say yes to everything for one night', 'Get a yes to everything for one night'],
      ['Watch a spicy movie together', 'Read a spicy story out loud together'],
    ],
  },
  {
    id: 'spicy-who', type: 'who', cat: 'spicyplay', spicy: true, emoji: '🫣', title: 'Most Likely To: Spicy',
    items: [
      'Initiate tonight', 'Send a spicy pic first', 'Get us caught somewhere risky', 'Be the loudest',
      'Want to go again', 'Fall asleep right after', 'Suggest something new in bed', 'Leave marks',
      'Get turned on at the worst possible time', 'Have a secret kink', 'Start something in the shower',
      'Break first in a teasing contest', 'Be into role-play', 'Rip clothes off', 'Get jealous in a hot way',
    ],
  },
  {
    id: 'spicy-nhie', type: 'nhie', cat: 'spicyplay', spicy: true, emoji: '🤭', title: 'Never Have I Ever: Spicy',
    items: [
      'Sent a nude', 'Had a sex dream about someone I know', 'Done it in a car', 'Been walked in on', 'Used a toy',
      'Faked it', 'Hooked up somewhere public', 'Watched porn with a partner', 'Done it in the shower', 'Tried role-play',
      'Been tied up', 'Had a one-night stand', 'Sexted in class or at work',
      'Thought about my partner in *that* way during something boring', 'Had phone sex', 'Been told I was loud',
    ],
  },
  {
    id: 'spicy-talk', type: 'open', cat: 'spicytalk', spicy: true, emoji: '🛏️', title: 'Pillow Talk',
    items: [
      'What’s something I do that turns you on instantly?',
      'What was going through your head the first time we hooked up?',
      'Describe your ideal night with me. Don’t leave things out.',
      'What’s a fantasy you’ve never said out loud?',
      'Where’s somewhere you’ve thought about doing it with me?',
      'What outfit do you want to see me in?',
      'What’s the hottest memory of us so far?',
      'What do you want me to do more of?',
      'Is there something you want to try but have been too shy to ask?',
      'What’s your favorite thing about my body?',
      'What do you want me to whisper in your ear?',
      'If you had me for a whole weekend with zero plans, what happens?',
    ],
  },
  {
    id: 'spicy-talk-2', type: 'open', cat: 'spicytalk', spicy: true, emoji: '💌', title: 'Confessions',
    items: [
      'When was the last time you thought about me in a not-so-innocent way? What were you doing?',
      'What’s something I wore that you couldn’t stop thinking about?',
      'What’s the most turned on you’ve been around me in public?',
      'Finish this: "Tonight I want you to…"',
      'What’s a sound or word that gets you every time?',
      'What do you want to try the next time we have a whole night?',
      'Rank: kissing, touching, teasing, talking. Explain yourself.',
      'What’s one rule you’d want for a "no rules" night?',
      'Describe the perfect spicy text from me.',
      'What’s something you liked that you never told me you liked?',
    ],
  },
];

// ───────────────────────── DAILY QUESTIONS ─────────────────────────
// One per day, both answer, answers stay hidden until you've both answered.
export const DAILY = [
  'What made you smile today?',
  'What’s one thing you love about me that you haven’t said in a while?',
  'If we could teleport anywhere for dinner tonight, where are we going?',
  'What’s a song you’ve had on repeat lately?',
  'What’s something small that would make tomorrow better for you?',
  'What’s a memory of us that randomly pops into your head?',
  'Rate your day 1–10 and tell me why.',
  'What’s something you’re looking forward to this week?',
  'What’s the best thing you ate recently?',
  'What’s a fear you’ve gotten over?',
  'If you could instantly be an expert at something, what would it be?',
  'What would your perfect lazy day with me look like?',
  'What’s a compliment you got once that you still think about?',
  'What’s a movie you think I NEED to watch?',
  'Describe me in one emoji. Explain.',
  'What’s one thing on your mind right now?',
  'What’s a weird food combo you secretly love?',
  'What was the highlight of your week?',
  'What’s something you want to learn this year?',
  'If we had a free weekend with no money limit, what are we doing?',
  'What’s the most "us" thing we do?',
  'What’s a place from your childhood you’d love to show me?',
  'What’s a tiny habit of mine you’d miss if it disappeared?',
  'What do you think I was like as a kid?',
  'If today had a theme song, what was it?',
  'What’s one thing you wish you had more time for?',
  'What’s a goal you want me to hold you to?',
  'Who’s someone you admire, and why?',
  'What’s your current comfort show or comfort food?',
  'What’s a date we haven’t done yet that you want to do?',
  'What’s something you’re proud of from this month?',
  'If you could relive one day with me, which would it be?',
  'What’s a random thing that made you think of me recently?',
  'What’s a hill you will die on?',
  'What’s one thing you’d tell your 15-year-old self?',
  'What’s your love language been craving lately?',
  'What’s a smell that instantly takes you back somewhere?',
  'What’s the best gift you’ve ever gotten?',
  'What’s something about our relationship you’re thankful for today?',
  'What’s one word for how you’re feeling right now?',
  'If we started a business together, what would it be?',
  'What’s a fun fact about you I might not know?',
  'What’s your favorite photo of us and why?',
  'What would you do with an extra hour every day?',
  'What’s a tradition from your family you love?',
  'What’s something that always cheers you up?',
  'What’s your dream job if money and school didn’t matter?',
  'What’s something you’ve changed your mind about recently?',
  'What’s the sweetest thing someone’s done for you?',
  'If you wrote a book about your life, what’s the title?',
  'What part of your day do you look forward to most?',
  'What would our couple name be?',
  'What’s a skill of mine you’re jealous of?',
  'What’s one thing you want to do together before the year ends?',
  'What’s a question you’ve always wanted to ask me?',
  'What’s the funniest thing that’s happened to us?',
  'What’s something you wish people understood about you?',
  'If you could have any animal as a pet (no rules), what is it?',
  'What’s one thing I do that makes you feel safe?',
  'What do you want more of in your life right now?',
  'What’s your guilty-pleasure song?',
  'What’s a moment you were really proud of me?',
  'What’s something you want to try cooking together?',
  'What’s the most spontaneous thing you’ve ever done?',
  'Where do you feel most like yourself?',
  'What’s a nickname you’d give me if you had to pick a new one?',
  'What’s one thing that stressed you out today?',
  'What’s the best advice you’ve ever been given?',
  'What’s something I could surprise you with that you’d love?',
  'If our relationship had a mascot, what would it be?',
  'What’s a rule you think every couple should have?',
  'What’s something you’ve never done but always wanted to?',
  'What three things would you bring to a deserted island (I don’t count)?',
  'What do you think we’ll laugh about in 10 years?',
  'What’s the most attractive thing about me that isn’t physical?',
  'What was the last thing that made you laugh really hard?',
  'What’s a small luxury you’d never give up?',
  'If you could switch lives with anyone for a day, who?',
  'What are you craving right now (food or otherwise 😏)?',
  'What do you love most about where you live?',
  'What’s one thing you want to tell me but keep forgetting?',
  'What’s your ideal weekend breakfast?',
  'What’s a celebrity you think I’d get along with?',
  'What’s the most beautiful place you’ve ever been?',
  'What’s something you do when nobody’s watching?',
  'What’s your favorite thing we’ve ever cooked or eaten together?',
  'What’s a quality you hope our future kids / pets get from me?',
  'What’s a question you wish people asked you more?',
  'If you could ask your future self one thing, what would it be?',
  'What do you want our next trip to be?',
  'What’s the best part about being with me? (be specific)',
  'What’s something you’re working on that I can cheer for?',
  'If tonight was totally free, what would you want us to do?',
  'What’s a song that feels like us?',
  'What’s something you’re bad at but enjoy anyway?',
  'What’s the most underrated thing about you?',
  'What’s one thing we should do this weekend?',
  'Finish the sentence: "I knew you were special when…"',
  'What do you think is the secret to a good relationship?',
  'What’s one thing you want to thank me for?',
];

// ───────────────────────── TRUTH OR DARE (in person) ─────────────────────────
export const TOD_LEVELS = [
  { id: 'sweet', label: 'Sweet', emoji: '🍬' },
  { id: 'flirty', label: 'Flirty', emoji: '😘' },
  { id: 'spicy', label: 'Spicy', emoji: '🔥', spicy: true },
];

export const TRUTHS = {
  sweet: [
    'What’s the first thing you noticed about me?',
    'What’s a habit of mine you secretly love?',
    'What’s the most embarrassing thing you’ve done to impress me?',
    'What did you tell your friends about me early on?',
    'What’s a song that reminds you of me?',
    'When was the last time you cried, and why?',
    'What’s your favorite photo of us?',
    'What’s a nickname you’ve thought about calling me but haven’t?',
    'What’s the cheesiest thing you’ve ever done for love?',
    'What’s one thing you’d never want to change about me?',
    'What’s your biggest fear about the future?',
    'What’s the weirdest thing you’ve googled lately?',
    'If you could relive one day with me, which one?',
    'What’s something you’ve pretended to like for me?',
    'What’s a secret talent you’ve never shown me?',
    'What’s the pettiest thing you’ve ever been mad about?',
  ],
  flirty: [
    'What’s the most attractive thing I do without realizing it?',
    'Where do you most like to be kissed?',
    'What’s the most romantic thing you’ve daydreamed about us doing?',
    'What outfit of mine is your favorite?',
    'When did you first want to kiss me?',
    'Rate our first kiss out of 10. Be honest.',
    'What’s something about me that still gives you butterflies?',
    'What’s the flirtiest text you’ve wanted to send me but didn’t?',
    'What part of me do you look at the most?',
    'What’s a compliment you’ve been holding back?',
    'What’s the cutest thing I do when I’m half asleep?',
    'What do I do that makes you want to grab me?',
    'What’s your favorite way to be cuddled?',
    'If you could kiss me anywhere in the world, where?',
    'What’s the moment you thought "wow, they’re hot"?',
    'What’s the most jealous you’ve been over me?',
  ],
  spicy: [
    'What’s your wildest fantasy involving me?',
    'What’s the hottest thing we’ve ever done?',
    'Where’s the riskiest place you’d want to do it with me?',
    'What’s something you want me to do to you tonight?',
    'What’s your favorite position with me, and why?',
    'Have you ever had a dream about us? Describe it.',
    'What sound do I make that drives you crazy?',
    'What’s something new you want to try in bed?',
    'What’s the most turned on you’ve been around me in public?',
    'What’s the sexiest thing I’ve ever said to you?',
    'If you could control me for 10 minutes, what would you have me do?',
    'What’s one thing you’ve been too shy to ask for?',
    'How long did you want me before we first hooked up?',
    'What’s your favorite thing I do with my hands?',
    'Describe our hottest memory like you’re telling a story.',
    'What’s the one thing I could text you that would make you come home immediately?',
  ],
};

export const DARES = {
  sweet: [
    'Give me your best pickup line.',
    'Do your best impression of me.',
    'Serenade me with the chorus of any love song.',
    'Show me the last 5 photos in your camera roll.',
    'Compliment me nonstop for 30 seconds.',
    'Slow dance with me for one whole song.',
    'Let me do your hair however I want.',
    'Talk in an accent for the next 3 rounds.',
    'Write a 4-line poem about me right now and read it out loud.',
    'Re-enact how we met, playing both roles.',
    'Read our very first texts out loud, dramatically.',
    'Let me pick your phone wallpaper for a week.',
    'Give me a piggyback ride around the room.',
    'Text a friend something nice about me right now.',
    'Let me post anything (nice) on your story.',
    'Do 10 push-ups while saying something you love about me each time.',
  ],
  flirty: [
    'Kiss me somewhere other than my lips.',
    'Whisper something flirty in my ear.',
    'Give me a 2-minute shoulder massage.',
    'Sit on my lap for the next round.',
    'Hold eye contact with me for 60 seconds without laughing.',
    'Kiss me like it’s the end of a movie.',
    'Trace a word on my back with your finger. I have to guess it.',
    'Send me a flirty text right now, even though I’m right here.',
    'Give me your sexiest look and hold it for 10 seconds.',
    'Let me choose where you kiss me next.',
    'Feed me something like we’re in a rom-com.',
    'Kiss my neck for 10 seconds.',
    'Cuddle me in your favorite position for 2 minutes. No phones.',
    'Dance for me for 30 seconds.',
    'Tell me, in detail, what you love about my lips.',
    'Take a cute selfie with me that you have to make your lock screen.',
  ],
  spicy: [
    'Take off one piece of clothing (your choice).',
    'Kiss me anywhere you want for 30 seconds.',
    'Blindfold me and kiss three different places. I have to guess where.',
    'Give me a lap dance for one song.',
    'Whisper exactly what you want to do to me later.',
    'Take off one piece of my clothing without using your hands.',
    'Touch me anywhere for 30 seconds — but no kissing allowed.',
    'Kiss slowly down my neck.',
    'Show me exactly how you like to be touched.',
    'Let me tie your hands for the next 3 rounds.',
    'Do a slow striptease of one item.',
    'Leave a mark somewhere only I’ll see.',
    'Make out with me for one full minute. Timer on.',
    'Give me a massage, shirt off.',
    'Pick any object in the room and use it creatively on me for one minute.',
    'Let me be in charge of your next dare.',
  ],
};

// ───────────────────────── DATE IDEAS ─────────────────────────
export const DATE_CATS = [
  { id: 'home', label: 'At home', emoji: '🏠' },
  { id: 'out', label: 'Out & about', emoji: '🌆' },
  { id: 'cheap', label: 'Free / cheap', emoji: '💸' },
  { id: 'adventure', label: 'Adventure', emoji: '🧗' },
  { id: 'spicy', label: 'Spicy night', emoji: '🔥', spicy: true },
];

export const DATES = {
  home: [
    'Blanket fort movie marathon with all the snacks',
    'Cook a dish from a country neither of you has been to',
    'At-home spa night: face masks, massages, candles',
    'Build-your-own-pizza competition — judge each other’s',
    'Recreate your first date at home',
    'Paint each other’s portraits (badly)',
    'Game night tournament — loser makes breakfast',
    'Make a playlist of "our songs" and dance in the kitchen',
    'Bake something ridiculous from a TikTok recipe',
    'Living room picnic by candlelight',
    'Two-person karaoke battle',
    'Puzzle + podcast night',
    'Write letters to each other to open in 5 years',
    'Blind taste test: chips, sodas, or candy — loser does dishes',
  ],
  out: [
    'Mini golf with a bet on it',
    'Find the best-rated dessert spot nearby and split three things',
    'Thrift store challenge: $10 to dress each other',
    'Bookstore date — pick a book for each other',
    'Arcade date — combine tickets for one prize',
    'Try a cuisine neither of you has ever had',
    'Watch the sunset from the highest spot around',
    'Go-karts',
    'Comedy show or open mic night',
    'Farmers market, then cook what you bought',
    'Aquarium or zoo — narrate the animals’ drama',
    'Bowling with a silly rule every frame',
    'Drive with no destination; take turns picking turns',
  ],
  cheap: [
    'Stargazing with a blanket and a star app',
    'Sunrise picnic',
    'Free museum day',
    'Walk somewhere new and rate every dog you see',
    'Library date — find the weirdest book',
    'Watch a movie from the year one of you was born',
    'Photo scavenger hunt around town',
    'Park + homemade sandwiches',
    'Hike a trail you haven’t done',
    'Teach each other something you’re good at',
    'Gas station snack haul — $5 limit each — then a late-night drive',
    'Sidewalk chalk art date',
  ],
  adventure: [
    'Day trip to a town you’ve never been to',
    'Kayaking or paddle-boarding',
    'Rock climbing gym',
    'Drive-in movie',
    'Horseback riding',
    'Hot springs or a swimming hole',
    'Escape room',
    'Camping overnight (or glamping)',
    'Take a dance class together (salsa, swing)',
    'Axe throwing',
    'Rent bikes or scooters and explore downtown',
    'Concert for an artist you barely know',
  ],
  spicy: [
    'Hotel night just because — pack light',
    'Dress up fancy, come home, undress each other slowly',
    'Massage night: oil, candles, and absolutely no rushing',
    'Truth or Dare on Spicy (it’s in the app 😉)',
    'Shower date with candles and a speaker',
    'Strip version of any card or board game',
    '"Yes night" — take turns asking for something',
    'Blindfold taste test that turns into more',
    'Re-create your hottest memory',
    'Outfit / lingerie reveal — the other rates the fit',
    'Each write a fantasy, read them out loud by candlelight',
    'Do the Desire Match together, then try one mutual yes',
  ],
};

export const LOVE_LANGS = {
  W: { name: 'Words of Affirmation', emoji: '💬', tip: 'Say it out loud. Texts, notes, specific compliments.' },
  Q: { name: 'Quality Time', emoji: '⏳', tip: 'Undivided attention. Phones away, plans made.' },
  G: { name: 'Receiving Gifts', emoji: '🎁', tip: 'Little "I thought of you" things count big.' },
  A: { name: 'Acts of Service', emoji: '🛠️', tip: 'Take something off their plate without being asked.' },
  T: { name: 'Physical Touch', emoji: '🤗', tip: 'Hugs, hand-holding, sitting close, random kisses.' },
};
